### ISSUE TITLE
Question about the statement that VHAP cannot render colors

### ISSUE THREAD

**Issue by ShenhanQian** [ChenVoid/MGA#1]
Dear authors, 

Congratulations on the paper! I noticed that the paper mentions twice that VHAP cannot render colors. This appears to be a misunderstanding, as VHAP is fundamentally a photometric optimization pipeline where color rendering is a core capability.

In fact, the default [output](https://github.com/ShenhanQian/VHAP/blob/main/asset/nersemble_038_EMO-1.gif) of VHAP includes colored rendering, as demonstrated in the fourth column of the linked example.

If I’ve misunderstood anything, please feel free to clarify. Otherwise, I hope you can update the statements to reflect this soon.

Best regards,
Shenhan

**Comment by ChenVoid** [comment]
Thank you very much for your review. May I kindly ask if the fourth column of the linked example refers to a mesh texture or a rendered RGB image?

**Comment by ShenhanQian** [comment]
The fourth column are the tracked FLAME models rendered with colored texture, the same thing as the qualitative results you show in the paper for other methods.

**Comment by ChenVoid** [comment]
Thank you for the reminder. We will update the statement as soon as possible.

**Comment by ChenVoid** [comment]
> The fourth column are the tracked FLAME models rendered with colored texture, the same thing as the qualitative results you show in the paper for other methods.

Thank you for the reminder. We will update the statement as soon as possible.

**Comment by ShenhanQian** [comment]
No problem. Please free to check the latest [commit](https://github.com/ShenhanQian/VHAP/commit/d8ce4e97a38c85bb22cfee5dacced09d51723b36) that adds colored rendering to the interactive viewer.
